CREATE TABLE [dbo].[CFItem]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
    [FullStatement] VARCHAR(3000) NOT NULL,
    [AlternativeLabel] VARCHAR(3000) NULL,
    [CFItemType] VARCHAR(200) NULL,
    [HumanCodingScheme] VARCHAR(200) NULL,
    [ListEnumeration] INT NULL,
    [AbbreviatedStatement] VARCHAR(3000) NULL,
    [ConceptKeywords] VARCHAR(200) NULL,
    [ConceptKeywordsId] UNIQUEIDENTIFIER NULL,
    [Notes] VARCHAR(MAX) NULL,
    [Language] VARCHAR(200) NULL,
    [EducationLevel] VARCHAR(200) NULL,
    [CFItemTypeId] UNIQUEIDENTIFIER NULL,
    [LicenseId] UNIQUEIDENTIFIER NULL,
    [StatusStartDate] DATE NULL, 
    [StatusEndDate] DATE NULL,
    [LastChangeDateTime] SMALLDATETIME NOT NULL,
    [CFDocumentId] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_CFItem_Id] PRIMARY KEY NONCLUSTERED([Id]),
    CONSTRAINT [FK_CFItem_CFDocumentId] FOREIGN KEY ([CFDocumentId]) REFERENCES [CFDocument]([Id]),
    CONSTRAINT [FK_CFItem_CFItemTypeId] FOREIGN KEY ([CFItemTypeId]) REFERENCES [CFItemType]([Id]),
    CONSTRAINT [FK_CFItem_ConceptKeywordsId] FOREIGN KEY ([ConceptKeywordsId]) REFERENCES [CFConcept]([Id]),
    CONSTRAINT [FK_CFItem_LicenseId] FOREIGN KEY ([LicenseId]) REFERENCES [CFLicense]([Id]),
)
