CREATE TABLE [dbo].[CFSubject]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
    [Title] VARCHAR(200) NOT NULL, 
    [HierarchyCode] VARCHAR(200) NOT NULL, 
    [Description] VARCHAR(200) NULL, 
    [LastChangeDateTime] SMALLDATETIME NOT NULL, 
    CONSTRAINT [PK_CFSubject_Id] PRIMARY KEY NONCLUSTERED([Id])
)
